name: Delete Azure Resource Group

on:
  workflow_dispatch: # Allows you to trigger the deletion manually
    inputs:
      resource_group_name: 'rg-github-actions-demo'
        description: 'Name of the Resource Group to delete'
        required: true
        type: string

jobs:
  delete-rg:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Authenticate to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets::AZURE_CREDENTIALS }}

      # Step 2: Delete the Resource Group
      - name: Delete Azure Resource Group
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group delete --name ${{ github.event.inputs.resource_group_name }} --yes --no-wait
